# Generated by Django 2.0.2 on 2019-04-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingCenter',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('plans_url', models.CharField(blank=True, max_length=255, null=True)),
                ('trial', models.CharField(blank=True, max_length=255, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
